In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv('Iris.csv')
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,5].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [10]:
from sklearn import preprocessing
lab_enc=preprocessing.LabelEncoder()
y=lab_enc.fit_transform(y)

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4)

In [59]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)


In [60]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=8)
classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=8)

In [61]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 2, 0, 2, 1, 1, 1, 1, 0, 0, 2, 0, 0, 2, 1, 1, 2, 1, 0, 2, 0, 2,
       2, 0, 0, 1, 0, 1, 2, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 2, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2], dtype=int64)

In [62]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
result=confusion_matrix(y_test,y_pred)
print('confusion matrix:\n',result)
res1=classification_report(y_test,y_pred)
print('C_r:\n',res1)
res2=accuracy_score(y_test,y_pred)
print('accuracy:\n',res2)

confusion matrix:
 [[20  0  0]
 [ 0 22  0]
 [ 0  0 18]]
C_r:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        22
           2       1.00      1.00      1.00        18

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60

accuracy:
 1.0
